/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

/*FACE CARE*/
export const storeProducts = [
  {
    id: 1,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 50 ML",
    img: "FACE-CARE/product-1.png",
    price: 23,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "ARGAN OIL FOR FACE AND BODY LAVENDER 50 ML",
    img: "FACE-CARE/product-2.png",
    price: 26,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of lavender, geranium and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "ARGAN OIL FOR FACE AND BODY SWEET ORANGE 50 ML",
    img: "FACE-CARE/product-3.png",
    price: 26,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of orange and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "ARGAN OIL FOR FACE AND BODY SANDALWOOD 50 ML",
    img: "FACE-CARE/product-4.png",
    price: 26,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argania Spinosa tree enriched with essential oil of sandalwood, bergamot and frankincense. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It doesn´t contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 250 ML",
    img: "FACE-CARE/product-5.png",
    price: 68,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "ARGAN OIL FOR FACE AND BODY LAVENDER 250 ML",
    img: "FACE-CARE/product-6.png",
    price: 68,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of lavender, geranium and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "ARGAN OIL FOR FACE AND BODY SWEET ORANGE 250 ML",
    img: "FACE-CARE/product-7.png",
    price: 80,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argan tree (Argania Spinosa) enriched with essential oil of orange and patchouli.  It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "ARGAN OIL FOR FACE AND BODY SANDALWOOD 250 ML",
    img: "FACE-CARE/product-8.png",
    price: 80,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of sandalwood, bergamot  and frankincense. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "SHEA BUTTER WITH ARGAN OIL 50 ML",
    img: "FACE-CARE/product-9.png",
    price: 12,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Shea butter with argan oil is designed for dry skin. It intensively nourishes, moisturizes and protects your skin from drying. It also helps to prevent premature ageing of skin and promotes its regeneration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "SHEA BUTTER WITH ARGAN OIL - LAVENDER 50 ML",
    img: "FACE-CARE/product-10.png",
    price: 12,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Shea butter with argan oil is designed for dry skin. It intensively nourishes, moisturizes and protects your skin from drying. It also helps to prevent premature ageing of skin and promotes its regeneration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "SHEA BUTTER WITH ARGAN OIL - SWEET ORANGE 50 ML",
    img: "FACE-CARE/product-11.png",
    price: 12,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Shea butter with argan oil is designed for dry skin. It intensively nourishes, moisturizes and protects your skin from drying. It also helps to prevent premature ageing of skin and promotes its regeneration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title:
      "ANTI-AGEING DAY CREAM WITH PRICKLY PEAR SEED OIL AND GREEN COFFEE EXTRACT 50 ML",
    img: "FACE-CARE/product-12.png",
    price: 53,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Innovative day cream with argan oil enriched with prickly pear seed oil and green coffee extract provides luxurious skin care. It contains natural active substances rich in amino acids, vitamin E and K, essential fatty acids and antioxidants. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "ORGANIC ANTI-AGEING DAY CREAM WITH ARGAN OIL 50 ML",
    img: "FACE-CARE/product-13.png",
    price: 26,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "A luxurious day cream with argan oil enriched with essential oil of ylang-ylang and nutmeg intensively nourishes the skin and promotes natural regeneration of the skin cells. It leaves the skin supple and silky soft. It is suitable for all skin types.It contains 91.9% of organic and 99% of natural ingredients of ethical origin.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title:
      "ANTI-AGEING NIGHT CREAM WITH PRICKLY PEAR SEED OIL AND GREEN COFFEE EXTRACT 50 ML",
    img: "FACE-CARE/product-14.png",
    price: 53,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Innovative night cream with argan oil enriched with prickly pear seed oil and a green coffee extract takes care of your skin while you are asleep. It contains natural active substances rich in amino acids, vitamin E and K, essential fatty acids and antioxidants. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: "LIP BALM MINT 5 ML",
    img: "FACE-CARE/product-15.png",
    price: 6,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Lip Balm containing organic argan oil and organic cocoa butter nourishes and moisturizes the lips. Beeswax creates a protective film and the lips are not dried.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: "LIP BALM HONEY 5 ML",
    img: "FACE-CARE/product-16.png",
    price: 6,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Lip Balm containing organic argan oil and organic cocoa butter nourishes and moisturizes the lips. Beeswax creates a protective film and the lips are not dried.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: "LIP BALM NATURAL 5 ML",
    img: "FACE-CARE/product-17.png",
    price: 6,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Lip Balm containing organic argan oil and organic cocoa butter nourishes and moisturizes the lips. Beeswax creates a protective film and the lips are not dried.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: "ROSE WATER 125 ML",
    img: "FACE-CARE/product-18.png",
    price: 19,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan 100% natural rose water is made from petals of the precious Damascus rose. It refreshes and intensely hydrates the skin. It is suitable for all skin types. It does not contain artificial additives or synthetic substances.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: "MOROCCAN KESSA GLOVE",
    img: "FACE-CARE/product-19.png",
    price: 10,
    category: "FACE CARE",
    company: "MOROCCAN SENSE",
    info:
      "Kessa Exfoliating Glove is an excellent  tool for perfect skin peeling and detoxification. It removes dead cells and your skin will be brighter and finer. Use it with your black soap.",
    inCart: false,
    count: 0,
    total: 0,
  },
  /*HAIR CARE*/
  {
    id: 20,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 50 ML",
    img: "HAIR-CARE/product-1.png",
    price: 23,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 21,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 250 ML",
    img: "HAIR-CARE/product-2.png",
    price: 68,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 22,
    title: "SHAMPOO WITH ARGAN OIL 300 ML",
    img: "HAIR-CARE/product-3.png",
    price: 24,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil Shampoo this gentle, nourishing, restorative and deeply cleansing shampoo has a high content of plant extracts, all of which have been carefully selected to promote healthy, lustrous and weightless hair.This unique formula is recommended for dry, coloured, damaged, dull, flat and lifeless hair.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 23,
    title: "ARGAN OIL SHAMPOO WITH BERGAMOT AND LITSEA CUBEBA OIL BLEND 250 ML",
    img: "HAIR-CARE/product-4.png",
    price: 20,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Organic Argan Oil Shampoo with Bergamot and Litsea Cubeba Oil Blend for very dry hair. Free of parabens, SLS and SLES.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 24,
    title:
      "ORGANIC ARGAN OIL CONDITIONER WITH BERGAMOT AND LITSEA CUBEBA OIL BLEND 250 ML",
    img: "HAIR-CARE/product-5.png",
    price: 22,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Organic Argan Oil Conditioner with Bergamot and Litsea Cubeba Oil Blend for very dry hair. Free of parabens, SLS and SLES.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 25,
    title: "CONDITIONER WITH ARGAN OIL 300 ML",
    img: "HAIR-CARE/product-6.png",
    price: 27,
    category: "HAIR CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil Conditioner this deeply hydrating conditioner is ideal for detangling and gently nourishing all hair types. It restores the perfect levels of hydration without weighing hair down. It has a high content of plant extracts, all of which have been carefully selected to promote healthy, lustrous and weightless hair.",
    inCart: false,
    count: 0,
    total: 0,
  },
  /*Body Care*/
  {
    id: 26,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 50 ML",
    img: "BODY-CARE/product-1.png",
    price: 23,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 27,
    title: "ARGAN OIL FOR FACE AND BODY LAVENDER 50 ML",
    img: "BODY-CARE/product-2.png",
    price: 26,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of lavender, geranium and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 28,
    title: "ARGAN OIL FOR FACE AND BODY SWEET ORANGE 50 ML",
    img: "BODY-CARE/product-3.png",
    price: 26,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of orange and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 29,
    title: "ARGAN OIL FOR FACE AND BODY SANDALWOOD 50 ML",
    img: "BODY-CARE/product-4.png",
    price: 26,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argania Spinosa tree enriched with essential oil of sandalwood, bergamot and frankincense. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It doesn´t contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 30,
    title: "ARGAN OIL FOR FACE, BODY AND HAIR 250 ML",
    img: "BODY-CARE/product-5.png",
    price: 68,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming from the Argan tree (Argania Spinosa). It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 31,
    title: "ARGAN OIL FOR FACE AND BODY LAVENDER 250 ML",
    img: "BODY-CARE/product-6.png",
    price: 80,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of lavender, geranium and patchouli. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 32,
    title: "ARGAN OIL FOR FACE AND BODY SANDALWOOD 250 ML",
    img: "BODY-CARE/product-7.png",
    price: 80,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argania Spinosa tree enriched with essential oil of sandalwood, bergamot  and frankincense. It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 33,
    title: "ARGAN OIL FOR FACE AND BODY SWEET ORANGE 250 ML",
    img: "BODY-CARE/product-8.png",
    price: 80,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "View larger Argan Oil is pure, 100% natural argan oil produced and cold pressed from the finest Argan kernels coming  from the Argan tree (Argania Spinosa) enriched with essential oil of orange and patchouli.  It is rich in vitamin E and contains omega 6 and 9 unsaturated fatty acids, polyphenols and antioxidants. It does not contain perfumes, chemical preservatives or additives.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 34,
    title: "MOROCCAN BLACK SOAP WITH ARGAN OIL - BITTER ORANGE 200 G",
    img: "BODY-CARE/product-9.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Black Soap is a 100% natural black soap that is used in the traditional Moroccan Hammam Spa. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 35,
    title: "BATH MARINE SALT - BITTER ORANGE 200 G",
    img: "BODY-CARE/product-10.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Marine Bath Salt is natural bath sea salt containing Laminaria seaweed and bitter orange essential oil. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 36,
    title: "BATH MARINE SALT - ROSEMARY 200 G",
    img: "BODY-CARE/product-11.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Marine Bath Salt is natural bath sea salt containing Laminaria seaweed and rosemary essential oil. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 37,
    title: "MOROCCAN CLAY RHASSOUL - 7 PLATNS 200 G",
    img: "BODY-CARE/product-12.png",
    price: 17,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Rhassoul Clay or moroccan clay is suitable for all skin types. The traditional product from the Moroccan mountains Atlas. It is formed by the natural combination of volcanic activity and geothermal changes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 38,
    title: "MOROCCAN BLACK SOAP WITH OLIVE OIL - EUCALYPTUS 200 G",
    img: "BODY-CARE/product-13.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Moroccan Sense Black Soap is a 100% natural black soap that is used in the traditional Moroccan Hammam Spa. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 39,
    title: "SHEA BUTTER WITH ARGAN OIL 50 ML",
    img: "BODY-CARE/product-14.png",
    price: 12,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info: "SHEA BUTTER WITH ARGAN OIL 50 ML",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 40,
    title: "SHEA BUTTER WITH ARGAN OIL - LAVENDER 50 ML",
    img: "BODY-CARE/product-15.png",
    price: 12,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info: "SHEA BUTTER WITH ARGAN OIL - LAVENDER 50 ML",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 41,
    title: "SHEA BUTTER WITH ARGAN OIL - SWEET ORANGE 50 ML",
    img: "BODY-CARE/product-16.png",
    price: 12,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Shea butter with argan oil is designed for dry skin. It intensively nourishes, moisturizes and protects your skin from drying. It also helps to prevent premature ageing of skin and promotes its regeneration.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 42,
    title: "ARGAN OIL BODY WASH WITH LAVENDER AND SANDALWOOD OIL BLEND 250 ML",
    img: "BODY-CARE/product-17.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Gentle, nutritious and intensely cleansing shower gel with organic argan oil and aloe vera extract. It is enriched with essential oils of lavender and sandalwood that help to calm and harmonize the mind and regenerate the tired body. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 43,
    title:
      "ARGAN OIL BODY WASH WITH SWEET ORANGE AND YLANG YLANG OIL BLEND 250 ML",
    img: "BODY-CARE/product-18.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Gentle, nutritious and intensely cleansing shower gel with organic argan oil and aloe vera extract  is enriched with essential oils of sweet orange and sandalwood that help to harmonize the mind and regenerate the tired body. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 44,
    title:
      "ARGAN OIL BODY LOTION WITH LAVENDER AND SANDALWOOD OIL BLEND 250 ML",
    img: "BODY-CARE/product-19.png",
    price: 20,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Body Lotion with organic argan oil, the juice of aloe vera, shea butter and coconut oil moisturizes the skin, leaving it velvety smooth. It is enriched with essential oils of lavender and sandalwood that soothe and harmonize the mind and regenerate the tired body. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 45,
    title:
      "ARGAN OIL BODY LOTION WITH SWEET ORANGE AND YLANG YLANG OIL BLEND 250 ML",
    img: "BODY-CARE/product-20.png",
    price: 20,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Gentle, nutritious and intensely cleansing shower gel with organic argan oil and aloe vera extract  is enriched with essential oils of sweet orange and sandalwood that help to harmonize the mind and regenerate the tired body. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 46,
    title: "NOURISHING HAND CREAM WITH ARGAN OIL - NATURAL 75 ML",
    img: "BODY-CARE/product-21.png",
    price: 17,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "enriched with aloe vera juice and shea butter. It is suitable for everyday care of hands, nails and cuticles. It has a light texture that makes it quickly absorbed into the skin and leaves no greasy film on the hands. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 47,
    title: "NOURISHING HAND CREAM WITH ARGAN OIL - SWEET ORANGE 75 ML",
    img: "BODY-CARE/product-22.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Nourishing hand cream with argan oil enriched with aloe vera juice, shea butter and sweet orange and peppermint oil blend is suitable for everyday care of hands, nails and cuticles. It has a light texture that makes it quickly absorbed into the skin and leaves no greasy film on the hands. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 48,
    title: "NOURISHING HAND CREAM WITH ARGAN OIL - LAVENDER 75 ML",
    img: "BODY-CARE/product-23.png",
    price: 18,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Nourishing hand cream with argan oil enriched with aloe vera juice, shea butter and lavender and jasmine oil blend is suitable for everyday care of hands, nails and cuticles. It has a light texture that makes it quickly absorbed into the skin and leaves no greasy film on the hands. It is suitable for all skin types.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 49,
    title: "MOROCCAN KESSA GLOVE",
    img: "BODY-CARE/product-24.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Kessa Exfoliating Glove is an excellent  tool for perfect skin peeling and detoxification. It removes dead cells and your skin will be brighter and finer. Use it with your black soap.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 50,
    title: "CRYSTAL DEODORANT 120 G",
    img: "BODY-CARE/product-25.png",
    price: 15,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "A natural deodorant made of antibacterial mineral salt - Potassium Alum. It eliminates  body odor and leaves no white stains on clothes. It provides protection for up to 24 hours. It is suitable for all skin types, both for women and men. It does not contain Aluminum and Aluminum Chlorohydrate",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 51,
    title: "GLYCERIN SOAP WITH CINNAMON 120 G",
    img: "BODY-CARE/product-26.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "This soft glycerin soap aromatized with Cinnamon, forms a creamy foam that will leave your skin feeling smooth and healthy with a fresh and pleasant fragrance. A true feeling of well being that can be experienced on a daily basis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 52,
    title: "GLYCERIN SOAP WITH GREEN TEA 120 G",
    img: "BODY-CARE/product-27.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info: "GLYCERIN SOAP WITH GREEN TEA 120 G",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 53,
    title: "GLYCERIN SOAP WITH MUSK 120 G",
    img: "BODY-CARE/product-28.png",
    price: 10,
    category: "BODY CARE",
    company: "apple",
    info:
      "View larger This soft glycerin soap aromatized with Musk, forms a creamy foam that will leave your skin feeling smooth and healthy with a fresh and pleasant fragrance. A true feeling of well being that can be experienced on a daily basis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 54,
    title: "GLYCERIN SOAP WITH NEROLI (ORANGE BLOSSOM) 120 G",
    img: "BODY-CARE/product-29.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "This soft glycerin soap aromatized with Neroli - Orange Blossom, forms a creamy foam that will leave your skin feeling smooth and healthy with a fresh and pleasant fragrance. A true feeling of well being that can be experienced on a daily basis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 55,
    title: "GLYCERIN SOAP WITH ROSE 120 G",
    img: "BODY-CARE/product-30.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "This soft glycerin soap aromatized with Rose, forms a creamy foam that will leave your skin feeling smooth and healthy with a fresh and pleasant fragrance. A true feeling of well being that can be experienced on a daily basis.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 56,
    title: "NATURAL SOAP WITH RHASSOUL CLAY AND ROSEMARY 120 G",
    img: "BODY-CARE/product-31.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info:
      "Glycerine-free natural soap with Moroccan clay Rhassoul and Rosemary",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 57,
    title: "NATURAL SOAP WITH ARGAN OIL 120 G",
    img: "BODY-CARE/product-32.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info: "Glycerine-free natural soap with Argan Oil",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 58,
    title: "NATURAL SOAP WITH ALMOND AND CEDAR 120 G",
    img: "BODY-CARE/product-33.png",
    price: 10,
    category: "BODY CARE",
    company: "MOROCCAN SENSE",
    info: "Glycerine-free natural soap with Almond Oil and Cedar essential oil",
    inCart: false,
    count: 0,
    total: 0,
  },
  /*Healthy Food*/

  {
    id: 59,
    title: "AMLOU PASTE 113 G",
    img: "HEALTHY-FOOD/product-1.png",
    price: 12,
    category: "HEALTHY FOOD",
    company: "MOROCCAN SENSE",
    info: "Amal paste from grilled almonds and argan oil",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 60,
    title: "Amal paste from grilled almonds and argan oil",
    img: "HEALTHY-FOOD/product-2.png",
    price: 15,
    category: "HEALTHY FOOD",
    company: "MOROCCAN SENSE",
    info: "Ideal for dips, salad dressings, pasta, fish and meat dishes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 61,
    title: "ARGAN OIL FOR FOOD 100 ML",
    img: "HEALTHY-FOOD/product-3.png",
    price: 15,
    category: "HEALTHY FOOD",
    company: "MOROCCAN SENSE",
    info: "Ideal for dips, salad dressings, pasta, fish and meat dishes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 62,
    title: "ARGAN OIL FOR FOOD 250 ML",
    img: "HEALTHY-FOOD/product-4.png",
    price: 28,
    category: "HEALTHY FOOD",
    company: "MOROCCANS SENSE",
    info: "Ideal for dips, salad dressings, pasta, fish and meat dishes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 63,
    title: "BENEFICIAL PACKAGE 100 ML + 113 G",
    img: "HEALTHY-FOOD/product-5.png",
    price: 26,
    category: "HEALTHY FOOD",
    company: "MOROCCAN SENSE",
    info:
      "The advantageous Christmas package includes: Culinary argan oil 100 ml and Amlou pasta 113 g",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 64,
    title: "BENEFICIAL PACKAGE 250 ML + 226 G",
    img: "HEALTHY-FOOD/product-6.png",
    price: 38,
    category: "HEALTHY FOOD",
    company: "MOROCCAN SENSE",
    info:
      "The advantageous Christmas package includes: Culinary argan oil 250 ml and Amlou pasta 226 g",
    inCart: false,
    count: 0,
    total: 0,
  },
  /*NewArrivals*/
  /*TopSold*/
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "img/product-1.png",
  price: 10,
  company: "google",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
